### ISSUE TITLE
How to change fonts? and how to modify the codeblock ?

### ISSUE THREAD

**Issue by depgod** [jaredkrinke/md2blog#30]

**Comment by jaredkrinke** [comment]
# Non-answer
My snarky non-answer would be: do you really need to change the font? It just uses the browser's default sans-serif font, which is usually adequate. One of md2blog's goals was to remove decisions around themes and fonts, because those get in the way to writing content.

Of course, I understand that answer is probably not what you were looking for, so here's an more direct answer:

# Fonts
First off, do you just want to change the font for aesthetic reasons, or is there a problem you're trying to solve? If the default font isn't working in some case (on some browser), that's something I should try to fix in md2blog itself.

As far as customizing the font, there isn't currently a way to do that, but it might be a reasonable customization to support. Until anything like that is implemented, your best option is to modify md2blog (or use another tool, of course).

Modifying md2blog requires [Deno](https://deno.land/), but there's at least no build process. Just fork the repository, change the CSS in style.css, and then point Deno to your new "main.ts" file (with appropriate permissions--[an example is in the quick start](https://jaredkrinke.github.io/md2blog/quick-start.html)).

# Code blocks
As far as how to modify the code block -- I'm afraid I don't understand. What are you trying to change about the code blocks?
