### ISSUE TITLE
<meta name="description"> != home page description

### ISSUE THREAD

**Issue by 4kelly** [jaredkrinke/md2blog#6]
While the `meta` tag site description should be a concise all text description tailored for SEO, the home page introduction content may want to include links, lists, or other. For example, a list of projects, books, or contact information.

Ex. 
Software Developer @ Company | Founder of <a href="https://www.kik.com/bots/roll/>Roll Bot</a>

**Comment by jaredkrinke** [comment]
I had a similar thought on this. I think I will add options for a header and footer with arbitrary HTML, with the header defaulting to the site description.

**Comment by jaredkrinke** [comment]
Here's my plan:

Add a new (optional) `layout` key to `site.json` for an object with the following properties (all optional):

* `headerPath`: Path to an HTML file (under and relative to the input directory) containing an arbitrary HTML fragment that will be inserted below the site title (note: the file will *not* be copied to the output directory)
* `footerPath`: Same but for content at the end of the page (e.g. copyright notice)
* `cssPath`: Similar, but inserted at the end of the CSS file

Note that the header fragment will *replace* the site description (because, as you noted, that description is text only and is used in the `description` meta tag).

I could argue that this is content and not configuration (which it sort of is), but having it all be optional means that "zero config" is still true by default.

My only reservation is that, like theming, perfecting these header and footer fragments provides yet another distraction from writing content.

**Comment by 4kelly** [comment]
My 2c. I agree that opening up theming may break the magic here. 

Breaking the problem up a bit.

For copyright, you could be very prescriptive and have it as an explicit arg, where you handle the theming.

```json
{
    "title": "Ryan Kelly",
    "description": "Software developer, privacy advocate, and father of two.",
    "url": "https://4kelly.com",
    "copyright": "Ryan Kelly CC BY-NC 4.0"
}
```

**Comment by 4kelly** [comment]
For zero config, no theming header:

There is a special `post` called `index.md` (or whatever)
> `content/posts/index.md`

This content is rendered to HTML and inserted into your template's `index` somewhere below the `title` and above the list of blog posts.

**Comment by 4kelly** [comment]
For footer, you could be even more opinionated. Something like:

Footer is composed of `copyright` and `contacts`. You handle all the theming.

```json
{
    "title": "Ryan Kelly",
    ...,
    "copyright": "Copyright © Ryan Kelly",
    "contacts": {
        "Email": "mailto:me@gmail.com",
        "Twitter": "https://twitter.com/4kelly_",
        "Github": "https://github.com/4kelly"
    }
}
```

**Comment by jaredkrinke** [comment]
Yeah, I may have gone overboard with the flexibility to inject arbitrary HTML, especially since md2blog currently requires no knowledge of HTML. Having some structured text/link fields seems more in the spirit of md2blog, at the cost of flexibility, but it also requires a more thoughtful design.

Just from looking at a (very biased sample of) blogs, the most common non-content items on the pages are (in no particular order):

* List of keywords/tags (already supported)
* Feed link (already supported... on the root page)
* Next/previous links (I considered adding these, but decided against it)
* Copyright, disclaimer (absolutely needed)
* Links to "about" page, Twitter, YouTube, resume, etc. (a good idea, but needs more thought around e.g. relative links, icons)
* Photo of the author (probably also worthwhile; likely a relative link)
* Author bio, location, company (the site description could be used for this today, although that's not ideal)
* Links to books, products, etc. (this would be a separate category of links...)
* Search (I do wonder if these even get used)
* Comments (some people might appreciate integrating with Disqus, but I'd really rather not go down that road)
* Tracking scripts (☹)
* Cookie banners (🤮)
* Ads (👎)

This could quickly get out of hand. I think the ones I could reasonably support would be:

* Copyright/disclaimer (in the footer; plain text or Markdown?)
* Links (in the header... but then what to do about the existing description-based subtitle?)
* Photo of the author (header or footer? Header on root page, but footer elsewhere?)
* Author bio (same location as photo? Plain text or Markdown? Would this need to reflow on mobile?)

If I allowed Markdown, then the copyright/bio fields could be inconveniently used to inject arbitrary HTML. I'm not completely opposed to this, but I think just handling it as plain text would be the simplest and most reliable choice.

**Comment by jaredkrinke** [comment]
I'm leaning towards plain text for all the fields (and everything optional, of course) for each of these:

* Header
  * Below the title on every page
* Author
  * Above article list on root/index pages
  * At the end of all other pages
* Footer
  * At the end of all pages (after any author info)

They would all have plain text and an option list of links (URLs, relative links, and relative links to Markdown files would be supported). The Author section could optionally contain a relative path to an image (with suggested aspect ratio of 1:1).

I'd probably implement header/footer first and then later sort out the details for the author section.

Example of possible schema:

```json
{
    "title": "Schemescape",
...
    "header": {
        "text": "This would replace the default description (or erase, if this field is undefined)",
        "links": {
            "About": "about.md",
            "Big project 1": "https://link"
        }
    },
    "author": {
        "image": "me.jpg",
        "text": "Here's my bio!",
        "links": {
            "GitHub": "https://github.com/whatever"
        }
    },
    "footer": {
        "text": "Copyright notice, most likely",
        "links": {
            "Privacy policy": "privacy.md"
        }
    },
...
}
```

This seems more convenient than what I originally proposed. Thanks for pulling me back from the brink, @4kelly :)

**Comment by 4kelly** [comment]
NP haha. Again, this is all just my 2c, this is your baby. 

I think we are on the same page that we want to add configuration only when absolutely necessary. I think the above would work, but I still wish there could be a way to simplify haha.

- As fas a priorities and splitting up the work, the most immediate need is probably the Copyright & Privacy Policy.

---

Here is another perspective on these efforts. The beautify that I see in md2blog right now is actually less about "zero config" and more about smart conventions _over_ configuration.

- Directories under posts are "tags", and there is support for easy filtering by tags automatically. (amazing)
- Any post under post is rendered as an html page in chronological order. 
- "Description" configs are cleverly re-used.

Im leaning towards adding more of these "obvious" conventions over configuration. Some ideas:

- Any markdown file inside the root of `content/` but not in `/posts` is a standalone page (ex: about.md) and added to a simple nav, or list of links somewhere. (again no configuration, just convention).
- We could buy time figuring out the "header" config, by simply providing a convention of adding an `about.md` somewhere. Users can add projects / external links / contact info there easily without bloating the main page.

**Comment by jaredkrinke** [comment]
Currently, any page not in `posts/` is in fact a standalone page. Adding all of these as a default list of links sounds like a great idea that I will explore.

One additional idea I've had is to make sure all pages are reachable at build time.

**Comment by jaredkrinke** [comment]
This has been updated for the next release:

* `header.text` can override the default subtitle
* `header.links` is a map of link labels to relative paths or absolute URLs; links appear directly below the subtitle
* If there are any non-post pages in the site root, links to these are used as the default for header links (if `header.links` is not specified)
  * For example, if there's an `about.md` page, an "About" link would be shown below the subtitle on every page
  * To remove the links, just set `header.links` to `{}`
